name: Docker Scout CVE Reusable Workflow

on:
  workflow_call:
    inputs:
      org_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: "dev"
    secrets:
      docker_username:
        required: true
      docker_pat:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          TAG="build-${GITHUB_RUN_NUMBER}-${SHORT_SHA}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Docker login (if needed for private images)
        run: echo "${{ secrets.docker_pat }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

      - name: Set BASE_IMAGE
        id: set-base
        run: |
            ORG_NAME="${{ inputs.org_name }}"
            IMAGE_NAME="${{ inputs.image_name }}"
            IMAGE_TAG="${{ inputs.image_tag }}"

            if [ -n "$ORG_NAME" ]; then
            BASE_IMAGE="${ORG_NAME}/${IMAGE_NAME}:${IMAGE_TAG}"
            else
            BASE_IMAGE="${IMAGE_NAME}:${IMAGE_TAG}"
            fi

            echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_OUTPUT

      - name: Build custom Nginx image
        uses: docker/build-push-action@v6
        with:
            context: .
            tags: custom-nginx:${{ steps.vars.outputs.tag }}
            build-args: |
                BASE_IMAGE=${{ steps.set-base.outputs.BASE_IMAGE }}
            push: false  # Set to true if you want to push to a registry

      - name: Run Docker Scout CVE scan
        env:
          DOCKER_SCOUT_HUB_USER: ${{ secrets.docker_username }}
          DOCKER_SCOUT_HUB_PASSWORD: ${{ secrets.docker_pat }}
        run: |
          set +e
          docker run --rm \
            -u root \
            -e DOCKER_SCOUT_HUB_USER \
            -e DOCKER_SCOUT_HUB_PASSWORD \
            -v /var/run/docker.sock:/var/run/docker.sock \
            docker/scout-cli \
            cves custom-nginx:${{ steps.vars.outputs.tag }} \
            --only-severity critical,high \
            --exit-code
          SCOUT_EXIT_CODE=$?
          set -e

          if [ $SCOUT_EXIT_CODE -eq 2 ]; then
            echo "::error title=Security Alert::Severe vulnerabilities found in custom-nginx image."
            exit 1
          elif [ $SCOUT_EXIT_CODE -ne 0 ]; then
            echo "::error title=Scanner Failure::Docker Scout failed with exit code $SCOUT_EXIT_CODE."
            exit 1
          else
            echo "No severe vulnerabilities found in custom-nginx image."
          fi